language: python
matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: '3.6'
install:
    # build miniworld container
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    - export REPO=miniworldproject/miniworld_core
    - pushd ~/build/miniworld-project/miniworld_core
    - BRANCH=$TRAVIS_BRANCH ci/build_container.sh

    # clone miniworld_playground
    - git clone https://github.com/miniworld-project/miniworld_playground.git
    - pushd miniworld_playground
script:
    - uname -a
    # run tests
    - docker-compose exec core pytest -x -s tests
after_success:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
    # push docker image
    - docker push $REPO:$TAG