version: '3.2'

services:
  core:
    image: miniworldproject/miniworld_core:${BRANCH-nightly}
    cap_add:
    - ALL
    privileged: true
    volumes:
    - /lib/modules:/lib/modules
    - type: bind
      source: ./
      target: /app/
    - type: bind
      source: ../miniworld_playground/examples
      target: /app/examples
    devices:
    # kvm access
    - "/dev/kvm:/dev/kvm"
    ports:
    - 5000:5000
    - 5001:5001
    environment:
      - MW_CONFIG=${MW_CONFIG}