version: '3.2'
# data volume for persistent data between containers and runs
volumes:
  data:

# TODO: what happens if the base image changes ?
services:
  core:
    image: miniworldproject/miniworld_core:${BRANCH-nightly}
    cap_add:
    - ALL
    privileged: true
    volumes:
    # for modprobe
    - /lib/modules:/lib/modules
    - data:/app
    devices:
    # kvm access
    - "/dev/kvm:/dev/kvm"
    # TODO: which docker-compose version do we need for that ?
    #restart_policy:
    #  condition: any
  interactive:
    image: miniworldproject/miniworld_core:nightly
    links:
    - core
    command: /bin/sleep 99999d
    volumes:
    - data:/app